-- 코드를 입력하세요
/*
입양은 갔는데 들어온 기록이 사라짐
ANIMAL_INS : AI , ANIMAL_OUTS : AO
ORDER : ANIMAL_ID순
*/

-- JOIN 사용
SELECT AO.ANIMAL_ID AS ANIMAL_ID, AO.NAME AS NAME 
FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI 
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID

-- 다른 풀이 : 서브쿼리
/*
SELECT ANIMAL_ID, NAME FROM ANIMAL_OUTS 
WHERE ANIMAL_ID NOT IN(SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID
*/
