-- 코드를 입력하세요
/*SELECT DATE_FORMAT(SALES_DATE,'%Y') AS Y, DATE_FORMAT(SALES_DATE,'%c') AS M, GENDER, COUNT(DISTINCT(UI.USER_ID)) AS USERS
FROM ONLINE_SALE OS JOIN USER_INFO UI 
ON OS.USER_ID=UI.USER_ID 
WHERE UI.GENDER IS NOT NULL 
GROUP BY Y,M,GENDER 
ORDER BY Y,M,GENDER*/
SELECT YEAR(SALES_DATE) AS Y, MONTH(SALES_DATE) AS M, GENDER, COUNT(DISTINCT(UI.USER_ID)) AS USERS
FROM ONLINE_SALE OS JOIN USER_INFO UI 
ON OS.USER_ID=UI.USER_ID 
WHERE UI.GENDER IS NOT NULL 
GROUP BY Y,M,GENDER 
ORDER BY Y,M,GENDER