-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
FROM  
    (SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) AS FAV 
     FROM REST_INFO) AS T
WHERE FAVORITES=FAV 
ORDER BY FOOD_TYPE DESC;


