-- 코드를 입력하세요
/*datediff : 입양일 - 보호시작일
limit 2 
order by 보호기간 제일 긴 순서
AI INS AO OUTS
*/
SELECT AI.ANIMAL_ID, AI.NAME FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY DATEDIFF(AO.DATETIME,AI.DATETIME) DESC LIMIT 2