-- 코드를 입력하세요
/*
조인써야함 
BOOK : B , BOOK_SALES : BS 
BOOK_ID가 같음
MONTH사용
GROUP : 카테고리별로
ORDER : 카테고리 ASC
*/
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES 
FROM BOOK B JOIN BOOK_SALES BS 
ON B.BOOK_ID=BS.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE,'%m') = 01
GROUP BY CATEGORY ORDER BY CATEGORY
