-- 코드를 입력하세요
/*
GROUP : 저자, 카테고리
저자ID 저자이름 카테고리 판매량()
BOOK B AUTHOR A BOOK_SALES BS
1월기준
*/

SELECT A.AUTHOR_ID,A.AUTHOR_NAME, T.CATEGORY, T.TOTAL_SALES FROM AUTHOR A
RIGHT JOIN 
(SELECT AUTHOR_ID, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES FROM BOOK B
RIGHT JOIN 
(SELECT * FROM BOOK_SALES 
WHERE DATE_FORMAT(sales_date,'%Y-%m') ='2022-01') BS 
ON B.BOOK_ID = BS.BOOK_ID 
GROUP BY AUTHOR_ID, CATEGORY) T
ON A.AUTHOR_ID = T.AUTHOR_ID
ORDER BY A.AUTHOR_ID, T.CATEGORY DESC
           