-- 코드를 입력하세요
/*
매출액 = ID X 판매량 
매출액 기준 내림차순, 상품코드 오름차순
PRODUCT P OFFLINE_SALE OS
GROUP : 코드별로 묶어줘야함
*/
SELECT P.PRODUCT_CODE, (SUM(OS.SALES_AMOUNT * P.PRICE)) AS SALES 
FROM PRODUCT P JOIN OFFLINE_SALE OS
ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE
