-- 코드를 입력하세요
/*
2022-05 기준
TOTAL_SALES = AMOUNT*PRICE
*/
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * FO.AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT FP JOIN
(SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT FROM FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m')='2022-05' GROUP BY PRODUCT_ID) FO
ON FP.PRODUCT_ID=FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID 