-- 코드를 입력하세요
/*
JOIN 혹은 서브쿼리 사용
출력값 재료성분과 총주문량
FIRST_HALF : FH, ICECREAM_INFO : II 
*/ 
SELECT II.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF FH JOIN ICECREAM_INFO II
ON II.FLAVOR = FH.FLAVOR GROUP BY II.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER