-- 코드를 입력하세요
/*
GROUP BY : 자동차별
조건 : 통풍시트, 열선시트, 가죽시트 LIKE "%시트"
카운트
*/
SELECT CAR_TYPE, COUNT(CAR_ID) AS CARS FROM CAR_RENTAL_COMPANY_CAR 
WHERE OPTIONS LIKE "%시트%"
GROUP BY CAR_TYPE ORDER BY CAR_TYPE