-- 코드를 입력하세요
/*
ANIMAL_INS : AI , ANIMAL_OUTS : AO
보호시작일 : AI.DATETIME
입양일 : AO.DATETIME
*/
SELECT AO.ANIMAL_ID AS ANIMAL_ID, AO.NAME AS NAME
FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI
ON AO.ANIMAL_ID=AI.ANIMAL_ID
WHERE AO.DATETIME < AI.DATETIME
ORDER BY AI.DATETIME